### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by joannagyory** [drivendataorg/nasa-airport-config-runtime#4]
Good morning, I don't have a lot of experience running code in Docker containers, so I'm not sure if this is an issue on my end, but when I try running the benchmark main.py in the Docker container, I get the error

sudo: unable to resolve host c62718ff46da: Temporary failure in name resolution

Googling this issue suggests editing  /etc/hosts and adding the hostname, but since Docker assigns a new hostname with each run, this solution doesn't work for me.

**Comment by r-b-g-b** [comment]
Hi @joannagyory, can you share a bit more about how you encountered this error?

How did you create the test data? For example from the [README.md/A small fake dataset](https://github.com/drivendataorg/nasa-airport-config-runtime#a-small-fake-dataset):

```sh
python scripts/generate_fake_dataset.py
```

How did you run the benchmark? For example from [README.md/Running the benchmark](https://github.com/drivendataorg/nasa-airport-config-runtime#running-the-benchmark):

```sh
make pull
make pack-benchmark
make test-benchmark
```

**Comment by r-b-g-b** [comment]
Also it does look like from the `example_log.txt` I just added that the `Temporary failure in name resolution` warning message is displayed in the normal, working submission. It doesn't appear to prevent the submission from running successfully; is that the case for you?

**Comment by joannagyory** [comment]
Hi @r-b-g-b, I had stopped it early when I saw that message under the assumption that it wasn't working properly, but you are right, if I let it proceed then it will create the submission successfully. Thanks for your response!

**Comment by r-b-g-b** [comment]
Glad to hear it. Closing this issue now; good luck!
